# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://devsres.com/marcelo/"
DefaultContentLanguage  = "pt"
title                   = "/dev/sres/marcelo"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = "devsres-marcelo"
googleAnalytics         = "UA-177944209"
pluralizeListTitles     = false
disableLanguages        = []
publishDir = "docs"

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
    author              = "HTML5UP and Hugo"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "/dev/sres/marcelo"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Marcelo Andrade"
    paragraph             = "<b>Sysop 2 SRE</b>"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/marcelo.jpg"
      shape               = "circle"
      width               = ""
      alt                 = "/dev/sre"

  [params.sidebar]
    about               = "SRE e Cloud Native solutions engineer.<br>Respirando software livre desde 1997"
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = ""
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.fr]
    LanguageCode        = "fr"
    LanguageName        = "Français"
    title               = ""
    description         = "Un thème par HTML5 UP, porté par Julio Pescador. Simplifié et amélioré par Patrick Collins. Multilingue par StatnMap. Propulsé par Hugo."
    weight              = 2

    [[Languages.fr.menu.main]]
      name              = "Accueil"
      identifier        = "home"
      url               = ""
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.fr.menu.main]]
      name              = "About"
      identifier        = "about"
      url               = "about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.fr.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.fr.menu.main]]
      name              = "Catégories"
      identifier        = "categories"
      url               = "categories/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 5

    [[Languages.fr.menu.main]]
      name              = "Contact"
      identifier        = "contact"
      url               = "contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

  [Languages.pl]
    LanguageCode        = "pl"
    LanguageName        = "Polski"
    title               = "Hugo Future Imperfect Slim po polsku"
    description         = "Motyw HTML5 UP, przeniesiony przez Julio Pescadora i wzbogacony przez Patricka Collinsa. Wielojęzyczny przez StatnMap. Zasilany przez Hugo."
    weight              = 2

    [[Languages.pl.menu.main]]
      name              = "Home"
      identifier        = "home"
      url               = ""
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.pl.menu.main]]
      name              = "O mnie"
      identifier        = "about"
      url               = "about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.pl.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.pl.menu.main]]
      name              = "Kategorie"
      identifier        = "categories"
      url               = "categories/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 5

    [[Languages.pl.menu.main]]
      name              = "Kontakt"
      identifier        = "contact"
      url               = "contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

  [Languages.pt]
    LanguageCode        = "pt"
    LanguageName        = "Português"
    title               = ""
    description         = ""
    weight              = 4

    [[Languages.pt.menu.main]]
      name              = "Início"
      identifier        = "home"
      url               = ""
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.pt.menu.main]]
      name              = "Sobre"
      identifier        = "about"
      url               = "about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.pt.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.pt.menu.main]]
      name              = "Categorias"
      identifier        = "categories"
      url               = "categories/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 5

    [[Languages.pt.menu.main]]
      name              = "Contato"
      identifier        = "contact"
      url               = "contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

  [Languages.de]
    LanguageCode        = "de"
    LanguageName        = "Deutsche"
    weight              = 5

  [Languages.es]
    LanguageCode        = "es"
    LanguageName        = "Española"
    weight              = 6

  [Languages.zh-CN]
    LanguageCode        = "zh-CN"
    LanguageName        = "中文"
    weight              = 7

  [Languages.zh-TW]
    LanguageCode        = "zh-TW"
    LanguageName        = "中文"
    weight              = 8

  [Languages.ja]
    LanguageCode        = "ja"
    LanguageName        = "日本語"
    weight              = 9

  [Languages.nl]
    LanguageCode        = "nl"
    LanguageName        = "Nederlands"
    weight              = 10

    [[Languages.nl.menu.main]]
      name              = "Home"
      identifier        = "home"
      url               = ""
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.nl.menu.main]]
      name              = "Over"
      identifier        = "about"
      url               = "about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.nl.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.nl.menu.main]]
      name              = "Categorieën"
      identifier        = "categories"
      url               = "categories/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 5

    [[Languages.nl.menu.main]]
      name              = "Contact"
      identifier        = "contact"
      url               = "contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

[social]
  # Coding Communities
  github                = "marcelo-devsres"
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  # deviantart            = ""
  # flickr                = "example"
  # behance               = ""
  # dribbble              = ""
  # Publishing Communities
  # wordpress             = ""
  # medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "mrrandrade"
  # linkedin_company      = "devsres"
  # foursquare            = ""
  # xing                  = ""
  # slideshare            = ""
  # Social Networks
  facebook              = "devsresnetwork"
  # googleplus            = ""
  # reddit                = "example"
  # quora                 = ""
  youtube               = "channel/UCgbbwB1Wxndh8urBPpyx9XA/"
  # vimeo                 = ""
  # whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
  #  wechat              = ""
  #  qq                  = "" # User ID Number
  instagram             = "marcelo_devsres"
  # tumblr                = ""
  twitter               = "marcelo_devsres"
  # strava                = ""
  # skype                 = ""
  # snapchat              = ""
  # pinterest             = "example"
  telegram              = "/dev/sres"
  #vine                  = ""
  #googlescholar         = ""
  #orcid                 = ""
  #researchgate          = "example"
  #keybase               = "example"
  #mastodon              = "example.com/@example"
  # Email
  # email                 = "example"
